
/* Gives the CSQC a chance to intercept centerprints. Return true if you wish the engine to otherwise ignore the centerprint. */
float CSQC_Parse_CenterPrint(string msg)	
{

}

/* Gives the CSQC a chance to intercept sprint/bprint builtin calls. CSQC should filter by the client's current msg setting and then pass the message on to the print command, or handle them itself. */
void CSQC_Parse_Print(string printmsg, float printlvl)
{

}